# Generated by Django 4.0 on 2021-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs'), ('MS', 'Ms')], max_length=3)),
                ('country', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=30)),
                ('birth_date', models.DateField(null=True)),
                ('comments', models.TextField()),
            ],
        ),
    ]
